### ISSUE TITLE
Add support for AVRO

### ISSUE THREAD

**Issue by hgm-king** [CallistoLabsNYC/samsa#17]

**Comment by WesWWagner** [comment]
Regarding adding support for Avro... typically most clients are written in a manner that expects the developer to interact with the avro and protobuf libraries directly for their serdes activity.

Can you expand on whether this is a suggestion to automate and abstract this behavior by intervening in consume and produce requests to automatically interface w/ schema and serdes activity ? This would be a break from the norms and standards of how most kafka clients work, but is something I have considered particularly useful if a good pattern were adopted to automate this and not force users of the client to manually code serdes activity.

**Comment by hgm-king** [comment]
Yes this is true, we will keep format agnostic, the users of the library will work with Avro or whichever format they choose.
