### ISSUE TITLE
Update Documentation & Readme to be current

### ISSUE THREAD

**Issue by hgm-king** [CallistoLabsNYC/samsa#74]
## Background
We have recently finished adding Compression and TLS support. Our README makes no mention of these two. Furthermore our examples in the README and the inline docs are out of date. 

**Note:** our readme and the [root level docs](https://docs.rs/samsa/latest/samsa/index.html) in `lib.rs` should match.

## ToDos:
1. Add a TLS section to the README & lib.rs docs
2. Add a Compression section to the README & lib.rs docs
3. Update the examples in the README & lib.rs docs

1 is covered by #71  and 2 is covered by #75

**Comment by hgm-king** [comment]
Hello @morukele ! yes of course. Let me put a description in this issue to give it appropriate scope. We are happy to have any contributions :)

**Comment by morukele** [comment]
@hgm-king, the description looks good to me. Could you assign the issue to me? I will work on it this evening.

**Comment by dhonig** [comment]
@morukele still want to take this issue on?  Let me know if you need assistance?

**Comment by morukele** [comment]
@dhonig I have updated it, and it got merged. I think the issue is still open because of the evolving nature of the crate, so there will always need to be an update of the `ReadMe`.

**Comment by hgm-king** [comment]
Yeah I think we need to refit this one for SASL which is upcoming, and then do a big pass over the whole README and doco to make sure we don't miss anything.

Also, @morukele we will want some feedback as a new-comer around "how is our messaging about library usage and examples, as well as the ease of use" :)

**Comment by hgm-king** [comment]
I think I will close this and make a new one to be more organized

**Comment by morukele** [comment]
@hgm-king sounds good to me. Could you expand on the meaning of SASL? 

Also, I will give feedback when you need it.

**Comment by dhonig** [comment]
@hgm-king @dhonig  got it in future lets link the PR's to the issue so history is clear.  Thanks!
