### ISSUE TITLE
Create Benchmarks vs  kafka-rust client

### ISSUE THREAD

**Issue by dhonig** [CallistoLabsNYC/samsa#89]
Performance was part of our reason for creating the Samsa library.
To help gain support for Samsa from the community we would like to create benchmarks against kafak-rust client and publish those in a page linked from the readme.md

These benchmarks can be done with the criterion crate which is already included in the project

**Comment by morukele** [comment]
@dhonig @hgm-king I agree with this, do you mind if I give this a shot? In terms of benchmarks, I am looking at the following metrics:
- size of crate binary.
- speed (producing and consuming).
- multi-partition performance. 
- TLS and Compression performance.

Let me know what you think about these metrics, and I look forward to your suggestions too.

**Comment by daniel-honig-clearscale** [comment]
I think those metrics are good. 
The most important is speed.

The criterion library is already included in the project.  

There is particular interest right now of how the crate performs vs kafka-rust ( librdkafka ).
Of course the starting point is to have solid benchmarks for Samsa.

I look forward to seeing what you come up with and I'll help when I have time!

**Comment by hgm-king** [comment]
I have added a benchmark for Consuming using Criterion in #93
